spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: root
      password: pwd
      authentication-database: admin
server:
  port: 8083

order_search_service_base_url: http://localhost:8081
product_info_service_base_url: http://localhost:8082
